"""Embed the processed portfolio chunks and upsert them into Pinecone.

Run from the portfolio_react directory:
    python backend/RAG/vector_store.py
"""

from __future__ import annotations

import json
import os
from itertools import islice
from pathlib import Path
from typing import Any, Iterator

from dotenv import load_dotenv

try:  # Supports both `python backend/RAG/vector_store.py` and package imports.
    from .embeddings import EMBEDDING_DIMENSION, embed_documents
except ImportError:
    from embeddings import EMBEDDING_DIMENSION, embed_documents


PROJECT_ROOT = Path(__file__).resolve().parents[2]
load_dotenv(PROJECT_ROOT / ".env")

CHUNKS_PATH = Path(__file__).resolve().parent / "data" / "portfolio_chunks.jsonl"
INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "portfolio-chatbot")
NAMESPACE = os.getenv("PINECONE_NAMESPACE", "portfolio")
EMBEDDING_BATCH_SIZE = 50
UPSERT_BATCH_SIZE = 100


def batched(items: list[dict[str, Any]], size: int) -> Iterator[list[dict[str, Any]]]:
    iterator = iter(items)
    while batch := list(islice(iterator, size)):
        yield batch


def load_chunks(path: Path = CHUNKS_PATH) -> list[dict[str, Any]]:
    """Load the JSONL artifact generated by loader.py."""
    if not path.is_file():
        raise FileNotFoundError(
            f"Processed chunks were not found at {path}. Run loader.py first."
        )
    chunks: list[dict[str, Any]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        item = json.loads(line)
        if not item.get("page_content") or not item.get("metadata", {}).get("document_id"):
            raise ValueError(f"Invalid chunk on line {line_number} in {path.name}.")
        chunks.append(item)
    if not chunks:
        raise ValueError("The processed chunk file is empty.")
    return chunks


def get_index():
    """Connect to the configured existing Pinecone index and check its dimension."""
    api_key = os.getenv("PINECONE_API_KEY")
    if not api_key:
        raise RuntimeError("PINECONE_API_KEY is missing from the project .env file.")
    try:
        from pinecone import Pinecone
    except ImportError as error:
        raise RuntimeError("Missing pinecone. Run: pip install google-genai pinecone") from error

    client = Pinecone(api_key=api_key)
    try:
        description = client.describe_index(INDEX_NAME)
    except Exception as error:
        raise RuntimeError(
            f"Could not find Pinecone index '{INDEX_NAME}'. Create it with dimension "
            f"{EMBEDDING_DIMENSION} and cosine metric, or set PINECONE_INDEX_NAME in .env."
        ) from error

    actual_dimension = getattr(description, "dimension", None)
    if actual_dimension is not None and int(actual_dimension) != EMBEDDING_DIMENSION:
        raise RuntimeError(
            f"Index '{INDEX_NAME}' has dimension {actual_dimension}, but the Gemini pipeline "
            f"creates {EMBEDDING_DIMENSION}-dimension vectors. Make them match before upserting."
        )
    return client.Index(INDEX_NAME)


def make_metadata(chunk: dict[str, Any]) -> dict[str, str]:
    """Use Pinecone-compatible flat metadata and retain the retrievable source text."""
    metadata = {str(key): str(value) for key, value in chunk["metadata"].items()}
    metadata["text"] = chunk["page_content"]
    return metadata


def upsert_chunks(chunks: list[dict[str, Any]], index=None) -> int:
    """Embed chunks in batches and upsert stable IDs, making reruns safe."""
    index = index or get_index()
    total = 0
    for chunk_batch in batched(chunks, EMBEDDING_BATCH_SIZE):
        embeddings = embed_documents([item["page_content"] for item in chunk_batch])
        vectors = [
            {
                "id": chunk["metadata"]["document_id"],
                "values": embedding,
                "metadata": make_metadata(chunk),
            }
            for chunk, embedding in zip(chunk_batch, embeddings, strict=True)
        ]
        for vector_batch in batched(vectors, UPSERT_BATCH_SIZE):
            index.upsert(vectors=vector_batch, namespace=NAMESPACE)
            total += len(vector_batch)
    return total


def main() -> None:
    chunks = load_chunks()
    index = get_index()  # Validate credentials and dimension before consuming embedding API calls.
    upserted = upsert_chunks(chunks, index=index)
    print(f"Upserted {upserted} portfolio chunks to '{INDEX_NAME}' in namespace '{NAMESPACE}'.")


if __name__ == "__main__":
    main()
